import Vue from 'vue';
import { DropzoneInstance } from './interfaces';
interface TypeHints {
    Emitter: Function;
    URL: Function;
    accept: Function;
    addFile: Function;
    cancelUpload: Function;
    clickableElements: any[];
    createThumbnail: Function;
    createThumbnailFromUrl: Function;
    defaultOptions: object;
    destroy: Function;
    disable: Function;
    drop: Function;
    element: object;
    emit: Function;
    enable: Function;
    enqueueFile: Function;
    enqueueFiles: Function;
    events: any[];
    files: any[];
    filesize: Function;
    getAcceptedFiles: Function;
    getActiveFiles: Function;
    getAddedFiles: Function;
    getExistingFallback: Function;
    getFallbackForm: Function;
    getFilesWithStatus: Function;
    getQueuedFiles: Function;
    getRejectedFiles: Function;
    getUploadingFiles: Function;
    handleFiles: Function;
    hiddenFileInput: object;
    init: Function;
    listeners: any[];
    off: Function;
    on: Function;
    paste: Function;
    previewsContainer: object;
    processFile: Function;
    processFiles: Function;
    processQueue: Function;
    removeAllFiles: Function;
    removeEventListeners: Function;
    removeFile: Function;
    resizeImage: Function;
    resolveOption: Function;
    setupEventListeners: Function;
    submitRequest: Function;
    updateTotalUploadProgress: Function;
    uploadFile: Function;
    uploadFiles: Function;
    version: string;
}
declare type UntypedKeys = Exclude<keyof TypeHints, keyof DropzoneInstance>;
declare type UntypedFields = Pick<TypeHints, UntypedKeys>;
export default class Dropzone extends Vue {
    instance: DropzoneInstance & UntypedFields;
    Emitter: Dropzone;
    URL: Dropzone;
    accept: Dropzone;
    addFile: Dropzone;
    cancelUpload: Dropzone;
    createThumbnail: Dropzone;
    createThumbnailFromUrl: Dropzone;
    destroy: Dropzone;
    disable: Dropzone;
    drop: Dropzone;
    emit: Dropzone;
    enable: Dropzone;
    enqueueFile: Dropzone;
    enqueueFiles: Dropzone;
    filesize: Dropzone;
    getAcceptedFiles: Dropzone;
    getActiveFiles: Dropzone;
    getAddedFiles: Dropzone;
    getExistingFallback: Dropzone;
    getFallbackForm: Dropzone;
    getFilesWithStatus: Dropzone;
    getQueuedFiles: Dropzone;
    getRejectedFiles: Dropzone;
    getUploadingFiles: Dropzone;
    handleFiles: Dropzone;
    init: Dropzone;
    off: Dropzone;
    on: Dropzone;
    paste: Dropzone;
    processFile: Dropzone;
    processFiles: Dropzone;
    processQueue: Dropzone;
    removeAllFiles: Dropzone;
    removeEventListeners: Dropzone;
    removeFile: Dropzone;
    resizeImage: Dropzone;
    resolveOption: Dropzone;
    setupEventListeners: Dropzone;
    submitRequest: Dropzone;
    updateTotalUploadProgress: Dropzone;
    uploadFile: Dropzone;
    uploadFiles: Dropzone;
    readonly clickableElements: any[];
    readonly defaultOptions: import("dropzone").DropzoneOptions;
    readonly element: object;
    readonly events: string[];
    readonly files: import("dropzone").DropzoneFile[];
    readonly hiddenFileInput: object;
    readonly listeners: any[];
    readonly previewsContainer: object;
    readonly version: string;
}
export {};
